// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package cachedb

import (
	"database/sql"
)

type DataBroadcastModule struct {
	ChannelType  string `json:"channel_type"`
	ChannelID    string `json:"channel_id"`
	ServiceID    int64  `json:"service_id"`
	ComponentTag int64  `json:"component_tag"`
	DownloadID   int64  `json:"download_id"`
	ModuleID     int64  `json:"module_id"`
	Version      int64  `json:"version"`
	Size         int64  `json:"size"`
	Info         []byte `json:"info"`
	Data         []byte `json:"data"`
	LastAccessed int64  `json:"last_accessed"`
	StoredBytes  int64  `json:"stored_bytes"`
}

type DataBroadcastModuleTombstone struct {
	ChannelType  string `json:"channel_type"`
	ChannelID    string `json:"channel_id"`
	ServiceID    int64  `json:"service_id"`
	ComponentTag int64  `json:"component_tag"`
	DownloadID   int64  `json:"download_id"`
	ModuleID     int64  `json:"module_id"`
	Version      int64  `json:"version"`
	EvictedAt    int64  `json:"evicted_at"`
}

type DataBroadcastResource struct {
	ChannelType     string         `json:"channel_type"`
	ChannelID       string         `json:"channel_id"`
	ServiceID       int64          `json:"service_id"`
	ComponentTag    int64          `json:"component_tag"`
	DownloadID      int64          `json:"download_id"`
	ModuleID        int64          `json:"module_id"`
	Version         int64          `json:"version"`
	Size            int64          `json:"size"`
	ResourceID      string         `json:"resource_id"`
	ContentLocation sql.NullString `json:"content_location"`
	ContentType     string         `json:"content_type"`
	Data            []byte         `json:"data"`
}
