// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package cachedb

import (
	"context"
	"database/sql"
)

const deleteModule = `-- name: DeleteModule :exec
DELETE FROM data_broadcast_modules WHERE channel_type=? AND channel_id=? AND service_id=? AND component_tag=? AND download_id=? AND module_id=? AND version=? AND size=?
`

type DeleteModuleParams struct {
	ChannelType  string `json:"channel_type"`
	ChannelID    string `json:"channel_id"`
	ServiceID    int64  `json:"service_id"`
	ComponentTag int64  `json:"component_tag"`
	DownloadID   int64  `json:"download_id"`
	ModuleID     int64  `json:"module_id"`
	Version      int64  `json:"version"`
	Size         int64  `json:"size"`
}

func (q *Queries) DeleteModule(ctx context.Context, arg DeleteModuleParams) error {
	_, err := q.db.ExecContext(ctx, deleteModule,
		arg.ChannelType,
		arg.ChannelID,
		arg.ServiceID,
		arg.ComponentTag,
		arg.DownloadID,
		arg.ModuleID,
		arg.Version,
		arg.Size,
	)
	return err
}

const deleteResources = `-- name: DeleteResources :exec
DELETE FROM data_broadcast_resources WHERE channel_type=? AND channel_id=? AND service_id=? AND component_tag=? AND download_id=? AND module_id=? AND version=? AND size=?
`

type DeleteResourcesParams struct {
	ChannelType  string `json:"channel_type"`
	ChannelID    string `json:"channel_id"`
	ServiceID    int64  `json:"service_id"`
	ComponentTag int64  `json:"component_tag"`
	DownloadID   int64  `json:"download_id"`
	ModuleID     int64  `json:"module_id"`
	Version      int64  `json:"version"`
	Size         int64  `json:"size"`
}

func (q *Queries) DeleteResources(ctx context.Context, arg DeleteResourcesParams) error {
	_, err := q.db.ExecContext(ctx, deleteResources,
		arg.ChannelType,
		arg.ChannelID,
		arg.ServiceID,
		arg.ComponentTag,
		arg.DownloadID,
		arg.ModuleID,
		arg.Version,
		arg.Size,
	)
	return err
}

const deleteTombstone = `-- name: DeleteTombstone :exec
DELETE FROM data_broadcast_module_tombstones WHERE channel_type=? AND channel_id=? AND service_id=? AND component_tag=? AND download_id=? AND module_id=? AND version=?
`

type DeleteTombstoneParams struct {
	ChannelType  string `json:"channel_type"`
	ChannelID    string `json:"channel_id"`
	ServiceID    int64  `json:"service_id"`
	ComponentTag int64  `json:"component_tag"`
	DownloadID   int64  `json:"download_id"`
	ModuleID     int64  `json:"module_id"`
	Version      int64  `json:"version"`
}

func (q *Queries) DeleteTombstone(ctx context.Context, arg DeleteTombstoneParams) error {
	_, err := q.db.ExecContext(ctx, deleteTombstone,
		arg.ChannelType,
		arg.ChannelID,
		arg.ServiceID,
		arg.ComponentTag,
		arg.DownloadID,
		arg.ModuleID,
		arg.Version,
	)
	return err
}

const getModule = `-- name: GetModule :one
SELECT info, data FROM data_broadcast_modules WHERE channel_type=? AND channel_id=? AND service_id=? AND component_tag=? AND download_id=? AND module_id=? AND version=? AND size=?
`

type GetModuleParams struct {
	ChannelType  string `json:"channel_type"`
	ChannelID    string `json:"channel_id"`
	ServiceID    int64  `json:"service_id"`
	ComponentTag int64  `json:"component_tag"`
	DownloadID   int64  `json:"download_id"`
	ModuleID     int64  `json:"module_id"`
	Version      int64  `json:"version"`
	Size         int64  `json:"size"`
}

type GetModuleRow struct {
	Info []byte `json:"info"`
	Data []byte `json:"data"`
}

func (q *Queries) GetModule(ctx context.Context, arg GetModuleParams) (GetModuleRow, error) {
	row := q.db.QueryRowContext(ctx, getModule,
		arg.ChannelType,
		arg.ChannelID,
		arg.ServiceID,
		arg.ComponentTag,
		arg.DownloadID,
		arg.ModuleID,
		arg.Version,
		arg.Size,
	)
	var i GetModuleRow
	err := row.Scan(&i.Info, &i.Data)
	return i, err
}

const getResources = `-- name: GetResources :many
SELECT size, resource_id, content_location, content_type, data FROM data_broadcast_resources WHERE channel_type=? AND channel_id=? AND service_id=? AND component_tag=? AND download_id=? AND module_id=? AND version=? ORDER BY CAST(resource_id AS INTEGER), resource_id
`

type GetResourcesParams struct {
	ChannelType  string `json:"channel_type"`
	ChannelID    string `json:"channel_id"`
	ServiceID    int64  `json:"service_id"`
	ComponentTag int64  `json:"component_tag"`
	DownloadID   int64  `json:"download_id"`
	ModuleID     int64  `json:"module_id"`
	Version      int64  `json:"version"`
}

type GetResourcesRow struct {
	Size            int64          `json:"size"`
	ResourceID      string         `json:"resource_id"`
	ContentLocation sql.NullString `json:"content_location"`
	ContentType     string         `json:"content_type"`
	Data            []byte         `json:"data"`
}

func (q *Queries) GetResources(ctx context.Context, arg GetResourcesParams) ([]GetResourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, getResources,
		arg.ChannelType,
		arg.ChannelID,
		arg.ServiceID,
		arg.ComponentTag,
		arg.DownloadID,
		arg.ModuleID,
		arg.Version,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResourcesRow
	for rows.Next() {
		var i GetResourcesRow
		if err := rows.Scan(
			&i.Size,
			&i.ResourceID,
			&i.ContentLocation,
			&i.ContentType,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoredBytes = `-- name: GetStoredBytes :one
SELECT stored_bytes FROM data_broadcast_modules WHERE channel_type=? AND channel_id=? AND service_id=? AND component_tag=? AND download_id=? AND module_id=? AND version=? AND size=?
`

type GetStoredBytesParams struct {
	ChannelType  string `json:"channel_type"`
	ChannelID    string `json:"channel_id"`
	ServiceID    int64  `json:"service_id"`
	ComponentTag int64  `json:"component_tag"`
	DownloadID   int64  `json:"download_id"`
	ModuleID     int64  `json:"module_id"`
	Version      int64  `json:"version"`
	Size         int64  `json:"size"`
}

func (q *Queries) GetStoredBytes(ctx context.Context, arg GetStoredBytesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getStoredBytes,
		arg.ChannelType,
		arg.ChannelID,
		arg.ServiceID,
		arg.ComponentTag,
		arg.DownloadID,
		arg.ModuleID,
		arg.Version,
		arg.Size,
	)
	var stored_bytes int64
	err := row.Scan(&stored_bytes)
	return stored_bytes, err
}

const getVersionModules = `-- name: GetVersionModules :many
SELECT size, info, data FROM data_broadcast_modules WHERE channel_type=? AND channel_id=? AND service_id=? AND component_tag=? AND download_id=? AND module_id=? AND version=?
`

type GetVersionModulesParams struct {
	ChannelType  string `json:"channel_type"`
	ChannelID    string `json:"channel_id"`
	ServiceID    int64  `json:"service_id"`
	ComponentTag int64  `json:"component_tag"`
	DownloadID   int64  `json:"download_id"`
	ModuleID     int64  `json:"module_id"`
	Version      int64  `json:"version"`
}

type GetVersionModulesRow struct {
	Size int64  `json:"size"`
	Info []byte `json:"info"`
	Data []byte `json:"data"`
}

func (q *Queries) GetVersionModules(ctx context.Context, arg GetVersionModulesParams) ([]GetVersionModulesRow, error) {
	rows, err := q.db.QueryContext(ctx, getVersionModules,
		arg.ChannelType,
		arg.ChannelID,
		arg.ServiceID,
		arg.ComponentTag,
		arg.DownloadID,
		arg.ModuleID,
		arg.Version,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVersionModulesRow
	for rows.Next() {
		var i GetVersionModulesRow
		if err := rows.Scan(&i.Size, &i.Info, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertResource = `-- name: InsertResource :exec
INSERT INTO data_broadcast_resources(channel_type,channel_id,service_id,component_tag,download_id,module_id,version,size,resource_id,content_location,content_type,data) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)
`

type InsertResourceParams struct {
	ChannelType     string         `json:"channel_type"`
	ChannelID       string         `json:"channel_id"`
	ServiceID       int64          `json:"service_id"`
	ComponentTag    int64          `json:"component_tag"`
	DownloadID      int64          `json:"download_id"`
	ModuleID        int64          `json:"module_id"`
	Version         int64          `json:"version"`
	Size            int64          `json:"size"`
	ResourceID      string         `json:"resource_id"`
	ContentLocation sql.NullString `json:"content_location"`
	ContentType     string         `json:"content_type"`
	Data            []byte         `json:"data"`
}

func (q *Queries) InsertResource(ctx context.Context, arg InsertResourceParams) error {
	_, err := q.db.ExecContext(ctx, insertResource,
		arg.ChannelType,
		arg.ChannelID,
		arg.ServiceID,
		arg.ComponentTag,
		arg.DownloadID,
		arg.ModuleID,
		arg.Version,
		arg.Size,
		arg.ResourceID,
		arg.ContentLocation,
		arg.ContentType,
		arg.Data,
	)
	return err
}

const moduleExists = `-- name: ModuleExists :one
SELECT 1 FROM data_broadcast_modules WHERE channel_type=? AND channel_id=? AND service_id=? AND component_tag=? AND download_id=? AND module_id=? AND version=? AND size=?
`

type ModuleExistsParams struct {
	ChannelType  string `json:"channel_type"`
	ChannelID    string `json:"channel_id"`
	ServiceID    int64  `json:"service_id"`
	ComponentTag int64  `json:"component_tag"`
	DownloadID   int64  `json:"download_id"`
	ModuleID     int64  `json:"module_id"`
	Version      int64  `json:"version"`
	Size         int64  `json:"size"`
}

func (q *Queries) ModuleExists(ctx context.Context, arg ModuleExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, moduleExists,
		arg.ChannelType,
		arg.ChannelID,
		arg.ServiceID,
		arg.ComponentTag,
		arg.DownloadID,
		arg.ModuleID,
		arg.Version,
		arg.Size,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const oldestExpiredModule = `-- name: OldestExpiredModule :one
SELECT channel_type, channel_id, service_id, component_tag, download_id, module_id, version, size FROM data_broadcast_modules WHERE last_accessed < ? ORDER BY last_accessed, channel_type, channel_id, service_id, component_tag, download_id, module_id, version, size LIMIT 1
`

type OldestExpiredModuleRow struct {
	ChannelType  string `json:"channel_type"`
	ChannelID    string `json:"channel_id"`
	ServiceID    int64  `json:"service_id"`
	ComponentTag int64  `json:"component_tag"`
	DownloadID   int64  `json:"download_id"`
	ModuleID     int64  `json:"module_id"`
	Version      int64  `json:"version"`
	Size         int64  `json:"size"`
}

func (q *Queries) OldestExpiredModule(ctx context.Context, lastAccessed int64) (OldestExpiredModuleRow, error) {
	row := q.db.QueryRowContext(ctx, oldestExpiredModule, lastAccessed)
	var i OldestExpiredModuleRow
	err := row.Scan(
		&i.ChannelType,
		&i.ChannelID,
		&i.ServiceID,
		&i.ComponentTag,
		&i.DownloadID,
		&i.ModuleID,
		&i.Version,
		&i.Size,
	)
	return i, err
}

const oldestModule = `-- name: OldestModule :one
SELECT channel_type, channel_id, service_id, component_tag, download_id, module_id, version, size FROM data_broadcast_modules ORDER BY last_accessed, channel_type, channel_id, service_id, component_tag, download_id, module_id, version, size LIMIT 1
`

type OldestModuleRow struct {
	ChannelType  string `json:"channel_type"`
	ChannelID    string `json:"channel_id"`
	ServiceID    int64  `json:"service_id"`
	ComponentTag int64  `json:"component_tag"`
	DownloadID   int64  `json:"download_id"`
	ModuleID     int64  `json:"module_id"`
	Version      int64  `json:"version"`
	Size         int64  `json:"size"`
}

func (q *Queries) OldestModule(ctx context.Context) (OldestModuleRow, error) {
	row := q.db.QueryRowContext(ctx, oldestModule)
	var i OldestModuleRow
	err := row.Scan(
		&i.ChannelType,
		&i.ChannelID,
		&i.ServiceID,
		&i.ComponentTag,
		&i.DownloadID,
		&i.ModuleID,
		&i.Version,
		&i.Size,
	)
	return i, err
}

const setAllLastAccessed = `-- name: SetAllLastAccessed :exec
UPDATE data_broadcast_modules SET last_accessed=?
`

func (q *Queries) SetAllLastAccessed(ctx context.Context, lastAccessed int64) error {
	_, err := q.db.ExecContext(ctx, setAllLastAccessed, lastAccessed)
	return err
}

const totalStoredBytes = `-- name: TotalStoredBytes :one
SELECT CAST(COALESCE(SUM(stored_bytes), 0) AS INTEGER) FROM data_broadcast_modules
`

func (q *Queries) TotalStoredBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalStoredBytes)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const touchModule = `-- name: TouchModule :exec
UPDATE data_broadcast_modules SET last_accessed=? WHERE channel_type=? AND channel_id=? AND service_id=? AND component_tag=? AND download_id=? AND module_id=? AND version=? AND size=?
`

type TouchModuleParams struct {
	LastAccessed int64  `json:"last_accessed"`
	ChannelType  string `json:"channel_type"`
	ChannelID    string `json:"channel_id"`
	ServiceID    int64  `json:"service_id"`
	ComponentTag int64  `json:"component_tag"`
	DownloadID   int64  `json:"download_id"`
	ModuleID     int64  `json:"module_id"`
	Version      int64  `json:"version"`
	Size         int64  `json:"size"`
}

func (q *Queries) TouchModule(ctx context.Context, arg TouchModuleParams) error {
	_, err := q.db.ExecContext(ctx, touchModule,
		arg.LastAccessed,
		arg.ChannelType,
		arg.ChannelID,
		arg.ServiceID,
		arg.ComponentTag,
		arg.DownloadID,
		arg.ModuleID,
		arg.Version,
		arg.Size,
	)
	return err
}

const trimTombstones = `-- name: TrimTombstones :exec
DELETE FROM data_broadcast_module_tombstones WHERE (channel_type,channel_id,service_id,component_tag,download_id,module_id,version) IN (SELECT channel_type,channel_id,service_id,component_tag,download_id,module_id,version FROM data_broadcast_module_tombstones ORDER BY evicted_at DESC,channel_type,channel_id,service_id,component_tag,download_id,module_id,version LIMIT -1 OFFSET ?)
`

func (q *Queries) TrimTombstones(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, trimTombstones, offset)
	return err
}

const upsertModule = `-- name: UpsertModule :exec
INSERT OR REPLACE INTO data_broadcast_modules(channel_type,channel_id,service_id,component_tag,download_id,module_id,version,size,info,data,last_accessed,stored_bytes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)
`

type UpsertModuleParams struct {
	ChannelType  string `json:"channel_type"`
	ChannelID    string `json:"channel_id"`
	ServiceID    int64  `json:"service_id"`
	ComponentTag int64  `json:"component_tag"`
	DownloadID   int64  `json:"download_id"`
	ModuleID     int64  `json:"module_id"`
	Version      int64  `json:"version"`
	Size         int64  `json:"size"`
	Info         []byte `json:"info"`
	Data         []byte `json:"data"`
	LastAccessed int64  `json:"last_accessed"`
	StoredBytes  int64  `json:"stored_bytes"`
}

func (q *Queries) UpsertModule(ctx context.Context, arg UpsertModuleParams) error {
	_, err := q.db.ExecContext(ctx, upsertModule,
		arg.ChannelType,
		arg.ChannelID,
		arg.ServiceID,
		arg.ComponentTag,
		arg.DownloadID,
		arg.ModuleID,
		arg.Version,
		arg.Size,
		arg.Info,
		arg.Data,
		arg.LastAccessed,
		arg.StoredBytes,
	)
	return err
}

const upsertTombstone = `-- name: UpsertTombstone :exec
INSERT OR REPLACE INTO data_broadcast_module_tombstones(channel_type,channel_id,service_id,component_tag,download_id,module_id,version,evicted_at) VALUES(?,?,?,?,?,?,?,?)
`

type UpsertTombstoneParams struct {
	ChannelType  string `json:"channel_type"`
	ChannelID    string `json:"channel_id"`
	ServiceID    int64  `json:"service_id"`
	ComponentTag int64  `json:"component_tag"`
	DownloadID   int64  `json:"download_id"`
	ModuleID     int64  `json:"module_id"`
	Version      int64  `json:"version"`
	EvictedAt    int64  `json:"evicted_at"`
}

func (q *Queries) UpsertTombstone(ctx context.Context, arg UpsertTombstoneParams) error {
	_, err := q.db.ExecContext(ctx, upsertTombstone,
		arg.ChannelType,
		arg.ChannelID,
		arg.ServiceID,
		arg.ComponentTag,
		arg.DownloadID,
		arg.ModuleID,
		arg.Version,
		arg.EvictedAt,
	)
	return err
}

const wasEvicted = `-- name: WasEvicted :one
SELECT 1 FROM data_broadcast_module_tombstones WHERE channel_type=? AND channel_id=? AND service_id=? AND component_tag=? AND download_id=? AND module_id=? AND version=?
`

type WasEvictedParams struct {
	ChannelType  string `json:"channel_type"`
	ChannelID    string `json:"channel_id"`
	ServiceID    int64  `json:"service_id"`
	ComponentTag int64  `json:"component_tag"`
	DownloadID   int64  `json:"download_id"`
	ModuleID     int64  `json:"module_id"`
	Version      int64  `json:"version"`
}

func (q *Queries) WasEvicted(ctx context.Context, arg WasEvictedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, wasEvicted,
		arg.ChannelType,
		arg.ChannelID,
		arg.ServiceID,
		arg.ComponentTag,
		arg.DownloadID,
		arg.ModuleID,
		arg.Version,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
