package observability

import "go.opentelemetry.io/otel/attribute"

const (
	AttrChannelID             attribute.Key = "channel.id"
	AttrChannelType           attribute.Key = "channel.type"
	AttrEPGCandidates         attribute.Key = "epg.candidates"
	AttrEPGNetworkID          attribute.Key = "epg.network_id"
	AttrEPGRetrievalTimeMS    attribute.Key = "epg.retrieval_time_ms"
	AttrEPGServiceID          attribute.Key = "epg.service_id"
	AttrEPGServices           attribute.Key = "epg.services"
	AttrEPGServicesObserved   attribute.Key = "epg.services.observed"
	AttrEPGServicesRemaining  attribute.Key = "epg.services.remaining"
	AttrEPGStaleAfter         attribute.Key = "epg.stale_after"
	AttrEventResource         attribute.Key = "event.resource"
	AttrEventType             attribute.Key = "event.type"
	AttrJobID                 attribute.Key = "job.id"
	AttrJobItemKind           attribute.Key = "job.item.kind"
	AttrJobKey                attribute.Key = "job.key"
	AttrJobName               attribute.Key = "job.name"
	AttrJobResult             attribute.Key = "job.result"
	AttrJobRetryCount         attribute.Key = "job.retry_count"
	AttrJobStatus             attribute.Key = "job.status"
	AttrOperation             attribute.Key = "operation"
	AttrProgramCount          attribute.Key = "program.count"
	AttrProgramCutoff         attribute.Key = "program.cutoff"
	AttrProgramFrom           attribute.Key = "program.from"
	AttrRemoteURL             attribute.Key = "remote.url"
	AttrResult                attribute.Key = "result"
	AttrRouteChannel          attribute.Key = "route.channel"
	AttrRouteCount            attribute.Key = "route.count"
	AttrRouteRemote           attribute.Key = "route.remote"
	AttrRouteType             attribute.Key = "route.type"
	AttrServiceAdded          attribute.Key = "service.added"
	AttrServiceCount          attribute.Key = "service.count"
	AttrServiceNewNetworks    attribute.Key = "service.new_networks"
	AttrServiceRemoved        attribute.Key = "service.removed"
	AttrSource                attribute.Key = "source"
	AttrStartupRetry          attribute.Key = "startup_retry"
	AttrStartupRetryMax       attribute.Key = "startup_retry.max"
	AttrStartupRetryTimeoutMS attribute.Key = "startup_retry.timeout_ms"
	AttrState                 attribute.Key = "state"
	AttrStreamActiveSession   attribute.Key = "stream.active_session"
	AttrTransport             attribute.Key = "transport"
	AttrTunedChannelID        attribute.Key = "tuned.channel.id"
	AttrTunedChannelType      attribute.Key = "tuned.channel.type"
	AttrTunerIndex            attribute.Key = "tuner.index"
	AttrTunerName             attribute.Key = "tuner.name"
	AttrWait                  attribute.Key = "wait"
)
